//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// moonsModbus.rc에서 사용되고 있습니다.
//
#define IDD_MOONSMODBUS_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_INDICATOR_COMM_STATUS       104
#define IDS_INDICATOR_MOTOR_STATUS      105
#define IDS_INDICATOR_INFOR             106
#define IDR_MAINFRAME                   128
#define IDC_MOONS_BTN_POSMODE_ABSMOVE_START 1008
#define IDC_MOONS_BTN_1                 1009
#define IDC_MOONS_BTN_2                 1010
#define IDC_MOONS_BTN_3                 1011
#define IDC_MOONS_BTN_04                1012
#define IDC_MOONS_BTN_05                1013
#define IDC_MOONS_BTN_4                 1014
#define IDC_MOONS_BTN_5                 1015
#define IDC_MOONS_CHK_MONITOR           1016
#define IDC_MOONS_CMB_POSMOVE_DIR       1019
#define IDC_MOONS_EDIT_POSMODE_ABSMOVE_POS 1020
#define IDC_MOONS_EDIT_POSMODE_ACCEL    1021
#define IDC_MOONS_EDIT_POSMODE_DECEL    1022
#define IDC_MOONS_EDIT_POSMODE_RELMOVE_POS 1023
#define IDC_MOONS_EDIT_POSMODE_VELOCITY 1024
#define IDC_GRP_MONITOR                 1026
#define IDC_MOONS_BTN_POSMODE_ABSMOVE_STOP 1027
#define IDC_GRP_POSMOVE_ABSMOVE         1028
#define IDC_LBL_ACTUALSPEED             1029
#define IDC_LBL_ALARMCODE               1030
#define IDC_GRP_POSMODE_RELMOVE         1031
#define IDC_MOONS_BTN_POSMODE_RELMOVE_START 1032
#define IDC_LBL_ENCODERPOSITION         1033
#define IDC_LBL_INTERVAL                1034
#define IDC_LBL_INTERVAL_UNIT           1035
#define IDC_LBL_INTERVAL2               1036
#define IDC_LBL_INTERVAL5               1037
#define IDC_MOONS_BTN_POSMODE_RELMOVE_STOP 1038
#define IDC_MOONS_BTN_6                 1039
#define IDC_LBL_POSMODE_ABSMOVE_POS     1047
#define IDC_LBL_POSMODE_ABSMOVE_POS_UNIT 1048
#define IDC_LBL_POSMODE_ACCEL           1049
#define IDC_LBL_POSMODE_ACCEL_UNIT      1050
#define IDC_LBL_POSMODE_DECEL           1051
#define IDC_LBL_POSMODE_RELMOVE_DIR     1053
#define IDC_LBL_POSMODE_RELMOVE_POS     1054
#define IDC_LBL_POSMODE_RELMOVE_POS_UNIT 1055
#define IDC_LBL_POSMODE_VELOCITY        1056
#define IDC_LBL_POSMODE_VELOCITY_UNIT   1057
#define IDC_MOONS_TXT_ACTUALSPEED       1064
#define IDC_MOONS_TXT_ALARMCODE         1065
#define IDC_MOONS_TXT_DRIVESTATUS       1068
#define IDC_MOONS_TXT_ENCODERPOSITION   1069
#define IDC_MOONS_TXT_INTERVAL          1070
#define IDC_MOONS_TXT_TARGETSPEED       1077

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
